source 'https://rubygems.org'

# Middleman Gems
gem 'middleman', '~> 4.1'
gem 'middleman-blog'

gem 'redcarpet', '~> 3.3', '>= 3.3.3'

# For feed.xml.builder
gem 'builder', '~> 3.0'

# Windows does not come with time zone data
gem 'tzinfo-data', platforms: [:mswin, :mingw, :jruby]

# For faster file watcher updates on Windows:
gem 'wdm', '~> 0.1.0', platforms: [:mswin, :mingw]
